### PR TITLE
Some fixes, one suggestion

### PR DESCRIPTION
**Pull request by rbeer**
Hey there!

Thanks for doing this! Especially, because you showed me slush and what it does. I'm gonna automate the hell out of my files now. ;)

214edea - "typo?"
Not sure, but the "slush-" seems double.

210b131 - "Fulfill POSIX standard newline"
You use a GNU/Linux/Unix shell style in the README, so I think this is nothing new to you. Just adding it for reference: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
(Makes me cringe every time, though. ^_^)

0644ca2 - "nodebb-plugin- is mandatory"
You can hardcode the nodebb-plugin- part of the plugin/folder name, since NodeBB actually requires folders to be named that way. Otherwise it wouldn't recognize it as a plugin.
https://github.com/nodebb/nodebb/blob/master/src/plugins.js#L307
To the user it's saving some keystrokes. But they add up. :)

c41e6f6 - "typo"
That's just what it is.

### CODE REVIEW

**Comment by rbeer** [comment]
Also, you are mixing double- and single-quotes. Don't know if that's intentional.

**Comment by jongarrison** [comment]
Thanks for digging through this stuff!  I was new to Slush just a few days ago and yeah it is great.

**Comment by jongarrison** [comment]
I merged three of your commits and I'm going to make a change based on your other commits related to requiring nodebb-plugin-.  Thanks for checking things over!

**Comment by jongarrison** [comment]
Here is how I handled the plugin name comment:

'''javascript
    {
    name: 'pluginNameShort',
    message: 'What is the plugin name, aka id (you can exclude the required prefix: "nodebb-plugin-...")?',
    default: defaults.possiblePluginName,
    filter: function(input) {
      return 'nodebb-plugin-' + input.replace('nodebb-plugin-', '');
    }
  },
'''

I find when this sort of required prefix thing comes up, there is often ambiguity.  Slush itself is not super clear about this, which is why you saw "slush-slush-" in a few places. :)  I think the approach above solves that pretty well.  The prompt change makes it clearer to the user and then even if they still put in the prefix, the code handles it correctly.

**Comment by jongarrison** [comment]
Thanks again!

**Comment by rbeer** [comment]
Nice! Indeed, that's why we are writing programs. Have them handle things so we don't have to care about it and can work intuitively, whatever we are used to. :)

**Pull request closed without merging**
